# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HarrisMatrix4QGIS
                                 A QGIS plugin
 Links a Harris Matrix in .graphml to Geometries
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-04-15
        copyright            : (C) 2024 by Brigit Danthine
        email                : brigitte.danthine@oeaw.ac.at
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HarrisMatrix4QGIS class from file HarrisMatrix4QGIS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .HarrisMatrix4QGIS import HarrisMatrix4QGIS
    return HarrisMatrix4QGIS(iface)
